### ISSUE TITLE
crash ingame 

### ISSUE THREAD

**Issue by CCrriimm** [AmrHuss/MarvelRivals-cheat#4]
![image](https://github.com/user-attachments/assets/8f060042-87a1-466c-a0a7-3c34188be1d7)

**Comment by CCrriimm** [comment]
it also lacks customization for aimbot like FOV, Keybind, etc.

**Comment by pvhost** [comment]
The problem occurs at GetSocketLocation

**Comment by AmrHuss** [comment]
fixed.
