### ISSUE TITLE
Not legit

### ISSUE THREAD

**Issue by OOFGODXZ** [AmrHuss/MarvelRivals-cheat#5]
when you fix the crashing can you add smoothing and keybinds for us legit players and also predations thanks man

**Comment by OOFGODXZ** [comment]
If you add me on discord id be a tester edensworld21

**Comment by minhnhatCoder** [comment]
I just add you in discord, can I ask smt about the code

**Comment by OOFGODXZ** [comment]
> I just add you in discord, can I ask smt about the code

Sure send a text

**Comment by minhnhatCoder** [comment]
Accept it, I already send a request , the acc name is kirito099ok
 in discord

**Comment by OOFGODXZ** [comment]
> Accept it, I already send a request , the acc name is kirito099ok
> 
>  in discord

Sent you a request
